"""Signal model for tracking strategy signals."""
from __future__ import annotations

import enum
from datetime import datetime, timezone
from typing import TYPE_CHECKING, Any

from sqlalchemy import JSON, Boolean, DateTime, Enum, Float, ForeignKey, String
from sqlalchemy.orm import Mapped, mapped_column, relationship

from .base import Base, TimestampMixin, generate_id

if TYPE_CHECKING:
    from .strategy import Strategy


class SignalDirection(str, enum.Enum):
    """Signal direction enum."""

    LONG = "long"
    SHORT = "short"
    CLOSE = "close"


class Signal(Base, TimestampMixin):
    """Strategy signal model with full audit trail.

    Tracks trading signals generated by strategies. Inherits created_at/updated_at
    from TimestampMixin for audit compliance.
    """

    id: Mapped[str] = mapped_column(String, primary_key=True, default=lambda: generate_id("sig"))
    strategy_id: Mapped[str] = mapped_column(String, ForeignKey("strategies.id"), nullable=False)
    symbol: Mapped[str] = mapped_column(String(20), nullable=False)

    # Signal details
    timestamp: Mapped[datetime] = mapped_column(
        DateTime,
        nullable=False,
        default=lambda: datetime.now(timezone.utc)  # Timezone-aware UTC timestamp
    )
    direction: Mapped[SignalDirection] = mapped_column(Enum(SignalDirection), nullable=False)
    price: Mapped[float] = mapped_column(Float, nullable=False)
    # Indicator values at signal time (explicit JSON type required for SQLAlchemy 2.0)
    indicators: Mapped[dict[str, Any] | None] = mapped_column(JSON)

    # Execution
    executed: Mapped[bool] = mapped_column(Boolean, default=False)

    # Relationships
    strategy: Mapped["Strategy"] = relationship("Strategy", back_populates="signals")

    def __repr__(self) -> str:
        return f"<Signal(id={self.id}, strategy_id={self.strategy_id}, direction={self.direction}, executed={self.executed})>"
