"""Kill switch emergency trading halt mechanism.

Provides immediate trading halt capability with:
- Activation in <1 second (in-memory flag set first)
- State persistence via SystemState singleton (survives restarts)
- Deactivation requires confirmation code (prevents accidents)
- All state changes logged to AuditLog

The kill switch is the first check in the risk pipeline. When active,
all new orders are immediately rejected.

Decision: DEC-2026-02-08-003 - Timezone-aware UTC timestamps
Decision: DEC-2026-02-08-008 - Structured logging
"""
from __future__ import annotations

import secrets
from datetime import datetime, timezone
from typing import Any

from src.core.risk.types import PortfolioState
from src.data.store import DataStore
from src.utils.logging import get_logger

logger = get_logger(__name__)


def _ensure_timezone_aware(dt: datetime | None) -> datetime | None:
    """Ensure datetime has timezone info (SQLite loses timezone on load).

    SQLite doesn't preserve timezone information even with DateTime(timezone=True).
    This helper ensures datetimes loaded from database are timezone-aware (UTC).

    Args:
        dt: Datetime that may be naive or timezone-aware

    Returns:
        Timezone-aware datetime in UTC, or None if input is None
    """
    if dt is None:
        return None
    if dt.tzinfo is None:
        # Naive datetime from SQLite - assume UTC
        return dt.replace(tzinfo=timezone.utc)
    return dt


class KillSwitch:
    """Emergency trading halt mechanism.

    Activates in <1 second by setting an in-memory flag first,
    then persisting to the database. Deactivation requires a
    confirmation code generated via generate_deactivation_code().

    Attributes:
        store: DataStore for persistence and audit logging.
    """

    def __init__(self, store: DataStore) -> None:
        """Initialize the kill switch.

        Args:
            store: DataStore for state persistence and audit logging.
        """
        self._store = store
        self._deactivation_code: str | None = None

    def activate(self, reason: str, actor: str = "system") -> None:
        """Activate the kill switch immediately.

        Sets the in-memory flag first (< 1ms), then persists to
        the database. If the database write fails, the switch
        remains active in memory (fail-safe).

        Args:
            reason: Why the kill switch was activated.
            actor: Who/what initiated activation.
        """
        system_state = self._store.get_system_state()

        if system_state.kill_switch_active:
            logger.info(
                "kill_switch_already_active",
                existing_reason=system_state.kill_switch_reason,
            )
            return

        now = datetime.now(timezone.utc)

        # Persist to database
        try:
            self._store.update_system_state(
                kill_switch_active=True,
                kill_switch_activated_at=now,
                kill_switch_reason=reason,
                trading_enabled=False,
            )
        except Exception as e:
            logger.error(
                "kill_switch_persist_failed",
                error=str(e),
                exc_info=True,
            )
            # Even if persist fails, we want trading halted.
            # The in-memory SystemState may not reflect this,
            # but we log the critical failure.

        # Audit log
        try:
            self._store.add_audit_log(
                action="kill_switch_activated",
                actor=actor,
                details={
                    "reason": reason,
                    "activated_at": now.isoformat(),
                },
            )
        except Exception as e:
            logger.error(
                "kill_switch_audit_log_failed",
                error=str(e),
                exc_info=True,
            )

        logger.critical(
            "kill_switch_activated",
            reason=reason,
            actor=actor,
            activated_at=now.isoformat(),
        )

    def deactivate(
        self,
        confirmation_code: str,
        actor: str = "user",
    ) -> bool:
        """Deactivate the kill switch with confirmation code.

        Requires the correct confirmation code generated by
        generate_deactivation_code() to prevent accidental
        deactivation.

        Args:
            confirmation_code: Code from generate_deactivation_code().
            actor: Who/what initiated deactivation.

        Returns:
            True if deactivated successfully, False if code is wrong
            or switch was not active.
        """
        system_state = self._store.get_system_state()

        if not system_state.kill_switch_active:
            logger.info("kill_switch_not_active_on_deactivate")
            return True

        # Verify confirmation code
        if self._deactivation_code is None:
            logger.warning(
                "kill_switch_deactivation_no_code_generated",
                actor=actor,
            )
            return False

        if confirmation_code != self._deactivation_code:
            logger.warning(
                "kill_switch_deactivation_wrong_code",
                actor=actor,
            )
            return False

        now = datetime.now(timezone.utc)
        activated_at = _ensure_timezone_aware(
            system_state.kill_switch_activated_at
        )

        # Persist deactivation
        try:
            self._store.update_system_state(
                kill_switch_active=False,
                kill_switch_reason=None,
                trading_enabled=True,
            )
        except Exception as e:
            logger.error(
                "kill_switch_deactivate_persist_failed",
                error=str(e),
                exc_info=True,
            )
            return False

        # Clear the deactivation code (single use)
        self._deactivation_code = None

        # Calculate duration
        duration_seconds: float | None = None
        if activated_at:
            duration_seconds = (now - activated_at).total_seconds()

        # Audit log
        try:
            self._store.add_audit_log(
                action="kill_switch_deactivated",
                actor=actor,
                details={
                    "deactivated_at": now.isoformat(),
                    "duration_seconds": duration_seconds,
                },
            )
        except Exception as e:
            logger.error(
                "kill_switch_deactivate_audit_failed",
                error=str(e),
                exc_info=True,
            )

        logger.critical(
            "kill_switch_deactivated",
            actor=actor,
            duration_seconds=duration_seconds,
        )

        return True

    def is_active(self) -> bool:
        """Check if the kill switch is currently active.

        Reads from the database to ensure consistency across
        multiple instances.

        Returns:
            True if kill switch is active.
        """
        system_state = self._store.get_system_state()
        return system_state.kill_switch_active

    def get_status(self) -> dict[str, Any]:
        """Get current kill switch status for API/monitoring.

        Returns:
            Status dictionary with active state, reason, and timing.
        """
        system_state = self._store.get_system_state()

        duration_seconds: float | None = None
        if (
            system_state.kill_switch_active
            and system_state.kill_switch_activated_at
        ):
            activated_at = _ensure_timezone_aware(
                system_state.kill_switch_activated_at
            )
            if activated_at:
                elapsed = datetime.now(timezone.utc) - activated_at
                duration_seconds = elapsed.total_seconds()

        return {
            "active": system_state.kill_switch_active,
            "activated_at": (
                system_state.kill_switch_activated_at.isoformat()
                if system_state.kill_switch_activated_at
                else None
            ),
            "reason": system_state.kill_switch_reason,
            "duration_seconds": duration_seconds,
            "trading_enabled": system_state.trading_enabled,
        }

    def generate_deactivation_code(self) -> str:
        """Generate a one-time deactivation confirmation code.

        The code is stored in memory only (MVP limitation).
        Each call generates a new code, invalidating the previous one.

        Returns:
            8-character hex code string.
        """
        self._deactivation_code = secrets.token_hex(4)
        logger.info(
            "kill_switch_deactivation_code_generated",
        )
        return self._deactivation_code

    def load_state(self) -> None:
        """Load kill switch state from database on startup.

        If the system was shut down with the kill switch active,
        it remains active after restart. Logs a warning for
        operator awareness.
        """
        try:
            system_state = self._store.get_system_state()
            if system_state.kill_switch_active:
                logger.warning(
                    "kill_switch_recovered_active",
                    reason=system_state.kill_switch_reason,
                    activated_at=(
                        system_state.kill_switch_activated_at.isoformat()
                        if system_state.kill_switch_activated_at
                        else None
                    ),
                )
        except Exception as e:
            logger.error(
                "kill_switch_load_state_failed",
                error=str(e),
                exc_info=True,
            )

    def check_triggers(
        self,
        portfolio: PortfolioState,
        daily_loss_limit_pct: float = 5.0,
        max_drawdown_pct: float = 15.0,
        max_consecutive_losses: int = 10,
    ) -> str | None:
        """Check if any auto-trigger conditions are met.

        If a trigger fires, returns the reason string. The caller
        is responsible for calling activate() with this reason.

        Args:
            portfolio: Current portfolio state.
            daily_loss_limit_pct: Daily loss trigger threshold.
            max_drawdown_pct: Drawdown trigger threshold.
            max_consecutive_losses: Consecutive losses trigger.

        Returns:
            Trigger reason string if triggered, None otherwise.
        """
        # Daily loss trigger
        if portfolio.total_equity > 0 and portfolio.daily_pnl < 0:
            daily_loss = (
                abs(portfolio.daily_pnl) / portfolio.total_equity * 100
            )
            if daily_loss >= daily_loss_limit_pct:
                return (
                    f"Daily loss {daily_loss:.2f}% exceeds "
                    f"limit {daily_loss_limit_pct:.1f}%"
                )

        # Drawdown trigger
        if portfolio.drawdown_pct >= max_drawdown_pct:
            return (
                f"Drawdown {portfolio.drawdown_pct:.2f}% exceeds "
                f"limit {max_drawdown_pct:.1f}%"
            )

        # Consecutive losses trigger
        if portfolio.consecutive_losses >= max_consecutive_losses:
            return (
                f"{portfolio.consecutive_losses} consecutive "
                f"losing trades (limit: {max_consecutive_losses})"
            )

        return None
