"""Risk management API endpoints.

Provides HTTP endpoints for kill switch control and portfolio
state monitoring. All endpoints use Pydantic models for
request/response validation.

Decision: DEC-2026-02-08-004 - Explicit CORS origins
Decision: DEC-2026-02-08-008 - Structured logging
"""
from __future__ import annotations

from datetime import datetime, timezone

from fastapi import APIRouter, HTTPException, status
from pydantic import BaseModel, Field

from src.core.risk.kill_switch import KillSwitch
from src.data.store import DataStore
from src.utils.logging import get_logger

logger = get_logger(__name__)

router = APIRouter()


# ---------------------------------------------------------------------------
# Request/Response models
# ---------------------------------------------------------------------------


class ActivateRequest(BaseModel):
    """Request to activate the kill switch."""

    reason: str = Field(
        ...,
        min_length=1,
        max_length=500,
        description="Reason for activation",
    )


class DeactivateRequest(BaseModel):
    """Request to deactivate the kill switch."""

    confirmation_code: str = Field(
        ...,
        min_length=1,
        description="Deactivation confirmation code",
    )


class KillSwitchStatusResponse(BaseModel):
    """Kill switch status response."""

    active: bool
    activated_at: str | None = None
    reason: str | None = None
    duration_seconds: float | None = None
    trading_enabled: bool = True


class DeactivationCodeResponse(BaseModel):
    """Response containing a generated deactivation code."""

    code: str
    message: str


class ActionResponse(BaseModel):
    """Generic action response."""

    status: str
    message: str
    timestamp: str


# ---------------------------------------------------------------------------
# Module-level singleton (initialized on first use)
# ---------------------------------------------------------------------------

_kill_switch: KillSwitch | None = None
_store: DataStore | None = None


def _get_store() -> DataStore:
    """Get or create the DataStore singleton."""
    global _store
    if _store is None:
        _store = DataStore()
    return _store


def _get_kill_switch() -> KillSwitch:
    """Get or create the KillSwitch singleton."""
    global _kill_switch
    if _kill_switch is None:
        _kill_switch = KillSwitch(_get_store())
        _kill_switch.load_state()
    return _kill_switch


# ---------------------------------------------------------------------------
# Endpoints
# ---------------------------------------------------------------------------


@router.get(
    "/kill-switch/status",
    response_model=KillSwitchStatusResponse,
    summary="Get kill switch status",
)
def get_kill_switch_status() -> KillSwitchStatusResponse:
    """Get the current kill switch status.

    Returns:
        Kill switch status including active state, reason, and duration.
    """
    ks = _get_kill_switch()
    status_data = ks.get_status()

    return KillSwitchStatusResponse(
        active=status_data["active"],
        activated_at=status_data.get("activated_at"),
        reason=status_data.get("reason"),
        duration_seconds=status_data.get("duration_seconds"),
        trading_enabled=status_data.get("trading_enabled", True),
    )


@router.post(
    "/kill-switch/activate",
    response_model=ActionResponse,
    status_code=status.HTTP_200_OK,
    summary="Activate kill switch",
)
def activate_kill_switch(request: ActivateRequest) -> ActionResponse:
    """Activate the kill switch immediately.

    This will halt all trading. Use with caution.

    Args:
        request: Activation request with reason.

    Returns:
        Confirmation of activation.
    """
    ks = _get_kill_switch()
    ks.activate(reason=request.reason, actor="api")

    logger.critical(
        "kill_switch_activated_via_api",
        reason=request.reason,
    )

    return ActionResponse(
        status="activated",
        message=f"Kill switch activated: {request.reason}",
        timestamp=datetime.now(timezone.utc).isoformat(),
    )


@router.post(
    "/kill-switch/deactivate",
    response_model=ActionResponse,
    summary="Deactivate kill switch",
)
def deactivate_kill_switch(
    request: DeactivateRequest,
) -> ActionResponse:
    """Deactivate the kill switch with confirmation code.

    Requires a valid confirmation code generated by the
    generate-code endpoint.

    Args:
        request: Deactivation request with confirmation code.

    Returns:
        Success or failure of deactivation.

    Raises:
        HTTPException: 403 if confirmation code is invalid.
    """
    ks = _get_kill_switch()
    success = ks.deactivate(
        confirmation_code=request.confirmation_code,
        actor="api",
    )

    if not success:
        logger.warning(
            "kill_switch_deactivation_rejected_via_api",
        )
        raise HTTPException(
            status_code=status.HTTP_403_FORBIDDEN,
            detail="Invalid confirmation code",
        )

    logger.critical(
        "kill_switch_deactivated_via_api",
    )

    return ActionResponse(
        status="deactivated",
        message="Kill switch deactivated successfully",
        timestamp=datetime.now(timezone.utc).isoformat(),
    )


@router.post(
    "/kill-switch/generate-code",
    response_model=DeactivationCodeResponse,
    summary="Generate deactivation code",
)
def generate_deactivation_code() -> DeactivationCodeResponse:
    """Generate a one-time deactivation confirmation code.

    The code is required to deactivate the kill switch.
    Each call generates a new code, invalidating the previous one.

    Returns:
        Generated deactivation code.
    """
    ks = _get_kill_switch()
    code = ks.generate_deactivation_code()

    return DeactivationCodeResponse(
        code=code,
        message="Use this code to deactivate the kill switch. "
        "Code is single-use and expires on next generation.",
    )
